### ISSUE TITLE
Credential issues.

### ISSUE THREAD

**Issue by LifeofDan-EL** [Open-Building-Management/emoncms#18]
Hello, I got to know about this Add-on and I am in the process of setting it up. I got the error that my username doesn't exist (it exists).

Error picture
![image](https://github.com/Open-Building-Management/emoncms/assets/45920948/08c80885-8303-47a0-a383-aa3e0bb3eb22)

EmonCMS dashboard
![image](https://github.com/Open-Building-Management/emoncms/assets/45920948/4b6dd699-286c-478a-b89c-cf6f04fb1941)

**Comment by alexandrecuer** [comment]
You need to register first, the login box shows that you did not register as there is a `register` link, just to the right of the login button

maybe I'm wrong but when you say that your username exists, you mean exists in home assistant

Even if your username exists in home assistant, right now you need to recreate in account in emoncms

there is no unified authentication system yet

**Comment by alexandrecuer** [comment]
You mean an account on https://www.emoncms.org/ ?

**Comment by LifeofDan-EL** [comment]
Exactly and the addon isn't letting me log in to it.

**Comment by alexandrecuer** [comment]
There is no link between the addon and emoncms.org

You need to create an account for the addon. Maybe in future I will remove this as the homeassistant account could be used instead but right now it is not the case

**Comment by LifeofDan-EL** [comment]
Thanks for your response.

**Comment by alexandrecuer** [comment]
You are welcome :-)
