### ISSUE TITLE
I can't create a new input.

### ISSUE THREAD

**Issue by LifeofDan-EL** [Open-Building-Management/emoncms#19]
Hello, it's me again :).

I got the addon to work, however, when I try to create a new device for input, it doesn't work. I plan to get data from my HA instance and send it to this addon through [this integration](https://www.home-assistant.io/integrations/emoncms_history/).

![image](https://github.com/Open-Building-Management/emoncms/assets/45920948/2fc38ef9-02dc-4466-b6a1-30f86d30e615)

**Comment by alexandrecuer** [comment]
Sorry i dont use and dont know this integration

You should better ask on :
https://community.openenergymonitor.org/

I think some members of this forum use this integration

Anyway a good starting point with inputs can be to read the input API Help at the top right of the page

**Comment by LifeofDan-EL** [comment]
The API Help docs says the input data has to be sent to a specified node to work. The integration just acts as a wrapper for the functionality.
 
 My major problem is not being able to create a new input device, so there's nothing to send data to. Which is weird because I can make feeds, graphs and others but nothing happens when I click on "new device" under input.

**Comment by alexandrecuer** [comment]
Did you finally manage to understand how to route data to the emoncms inputs ? Normally it is quite simple if you have a certain knowledge of MQTT and of rest API.  It's far less complicated than finding your way into grafana for example...

**Comment by LifeofDan-EL** [comment]
Yes, I did get it to work. So I had to use the MQTT  statestream integration, and then I got your addon to communicate with it. Thanks a lot. 
![image](https://github.com/Open-Building-Management/emoncms/assets/45920948/6e1382bc-b187-43ab-ad21-49461ccb8816)
