### ISSUE TITLE
Missing "Sync Interval" option in Sync module

### ISSUE THREAD

**Issue by Alibloke** [Open-Building-Management/emoncms#24]
I'm running Docker image alexjunk/emoncms (low-write 11.6.1) and need to sync my feeds with with emoncms.org.  I can sync manually, but there's a missing button to change the sync interval.  How can I automatically sync?

Expected:
![image](https://github.com/user-attachments/assets/808acbf1-ada1-48dd-b2e3-04f2994f4ccf)

Actual:
![image](https://github.com/user-attachments/assets/d73193f6-d33b-447d-b5e2-f4c9afd26b5f)

**Comment by alexandrecuer** [comment]
> How can I automatically sync?
I dont think so as the sync service is not running and cannot run as designed on a docker container. I guess the emoncms_sync is a systemd service and so that is not compatible with docker. To run on a container, it has to be migrated to an s6-overlay longtime runner...

**Comment by alexandrecuer** [comment]
first you need an image with sync 3.1.7
so actually, the only tag which could be OK is alexjunk/emoncms:alpine3.19.1_emoncms11.6.4

see changelog here : https://github.com/Open-Building-Management/emoncms/discussions/8

**Comment by Alibloke** [comment]
Thanks @alexandrecuer I tried that image but as you predicted systemctl seems to be needed to run the sync service:
`sh: systemctl: not found`

**Comment by alexandrecuer** [comment]
you can try this one alexjunk/themis:alpine3.19_emoncms11.6.4
I've adapted the sync process to an s6 long runner
tell me if it works....

**Comment by alexandrecuer** [comment]
@Alibloke : should be OK now, you will still have the message : `emoncms_sync service is not running` but the sync should work fine.

```
docker pull alexjunk/emoncms:alpine3.20_emoncms11.6.5
```
or use the latest tag :
```
docker pull alexjunk/emoncms
```

**Comment by Alibloke** [comment]
That seems to work.  Much appreciated @alexandrecuer !
